-- H2 인메모리 DB용 Stock 테이블 DDL
CREATE TABLE IF NOT EXISTS STOCK (
    PRODUCT_ID BIGINT NOT NULL PRIMARY KEY,
    QUANTITY INT NOT NULL DEFAULT 0,
    RESERVED_QUANTITY INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS IDX_STOCK_PRODUCT_ID ON STOCK(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS IDX_STOCK_QUANTITY ON STOCK(QUANTITY);
CREATE INDEX IF NOT EXISTS IDX_STOCK_UPDATED_AT ON STOCK(UPDATED_AT);

-- 재고 체크를 위한 뷰
CREATE OR REPLACE VIEW V_AVAILABLE_STOCK AS
SELECT
    PRODUCT_ID,
    QUANTITY,
    RESERVED_QUANTITY,
    (QUANTITY - RESERVED_QUANTITY) AS AVAILABLE_QUANTITY,
    CREATED_AT,
    UPDATED_AT
FROM STOCK
WHERE QUANTITY > 0;

-- 테스트 데이터 삽입
INSERT INTO STOCK (PRODUCT_ID, QUANTITY, RESERVED_QUANTITY) VALUES
(1, 100, 0),
(2, 50, 10),
(3, 25, 5),
(4, 0, 0),
(5, 200, 20);